### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by farice** [raphaelgyory/django-rest-messaging#2]
Hi there! I'm quite interesting in your package and was hoping to give it a test run.

Unfortunately, after installing all the dependencies and completing the setup, when I attempt to create a new thread on /messaging/threads/ I am given the error: `TypeError at /messaging/threads/
expected string or buffer`.

Have you encountered this before? I am using DRF 3.4.3.

Thanks for your help. Also, I can't find the directory to build the documentation and it seems there are no references online, so I'm having trouble learning about your software in general.

**Comment by farice** [comment]
It seems that the issue traces to the lack of a participant parameter being passed (thus one of the ids is 'null' and can't be parsed properly. 

However, my HTML form only renders with a single POST option: name. 

Any idea why there's a lack of the ability to input the 'participants' parameter?

**Comment by farice** [comment]
Thanks for your help Raphael, that was very informative.

I'll let you know what I'm able to pull together after I read up on React.

Faris

**Comment by raphaelgyory** [comment]
Hi Faris, you are welcome!

Any feedback would be much appreciated! 

Raphael 

Envoyé de mon iPhone
